/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface MatchOptions {
  threshold?: number
  scale?: number
}
export interface MatchResult {
  found: boolean
  x?: number
  y?: number
  confidence: number
}
export declare function templateMatch(haystackBuffer: Buffer, needleBuffer: Buffer, options?: MatchOptions | undefined | null): MatchResult
